# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0bservice_api\"/\n\x11WifiConfigRequest\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x0c\n\x04pass\x18\x02 \x01(\t\"9\n\x12WifiConfigResponse\x12#\n\x06result\x18\x01 \x01(\x0e\x32\x13.service_api.Result\"\x9e\x01\n\x13WifiI2CRelayRequest\x12>\n\rwrite_request\x18\x01 \x01(\x0b\x32%.service_api.WifiI2CRelayWriteRequestH\x00\x12<\n\x0cread_request\x18\x02 \x01(\x0b\x32$.service_api.WifiI2CRelayReadRequestH\x00\x42\t\n\x07request\"\xd7\x01\n\x14WifiI2CRelayResponse\x12@\n\x0ewrite_response\x18\x01 \x01(\x0b\x32&.service_api.WifiI2CRelayWriteResponseH\x00\x12>\n\rread_response\x18\x02 \x01(\x0b\x32%.service_api.WifiI2CRelayReadResponseH\x00\x12\x31\n\x12undefined_response\x18\x03 \x01(\x0e\x32\x13.service_api.ResultH\x00\x42\n\n\x08response\"M\n\x18WifiI2CRelayWriteRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\r\x12\x12\n\ntimeout_ms\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"@\n\x19WifiI2CRelayWriteResponse\x12#\n\x06result\x18\x01 \x01(\x0e\x32\x13.service_api.Result\"N\n\x17WifiI2CRelayReadRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\r\x12\x12\n\ntimeout_ms\x18\x02 \x01(\r\x12\x0e\n\x06length\x18\x03 \x01(\r\"M\n\x18WifiI2CRelayReadResponse\x12#\n\x06result\x18\x01 \x01(\x0e\x32\x13.service_api.Result\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c*3\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULT']._serialized_start=821
  _globals['_RESULT']._serialized_end=872
  _globals['_WIFICONFIGREQUEST']._serialized_start=30
  _globals['_WIFICONFIGREQUEST']._serialized_end=77
  _globals['_WIFICONFIGRESPONSE']._serialized_start=79
  _globals['_WIFICONFIGRESPONSE']._serialized_end=136
  _globals['_WIFII2CRELAYREQUEST']._serialized_start=139
  _globals['_WIFII2CRELAYREQUEST']._serialized_end=297
  _globals['_WIFII2CRELAYRESPONSE']._serialized_start=300
  _globals['_WIFII2CRELAYRESPONSE']._serialized_end=515
  _globals['_WIFII2CRELAYWRITEREQUEST']._serialized_start=517
  _globals['_WIFII2CRELAYWRITEREQUEST']._serialized_end=594
  _globals['_WIFII2CRELAYWRITERESPONSE']._serialized_start=596
  _globals['_WIFII2CRELAYWRITERESPONSE']._serialized_end=660
  _globals['_WIFII2CRELAYREADREQUEST']._serialized_start=662
  _globals['_WIFII2CRELAYREADREQUEST']._serialized_end=740
  _globals['_WIFII2CRELAYREADRESPONSE']._serialized_start=742
  _globals['_WIFII2CRELAYREADRESPONSE']._serialized_end=819
# @@protoc_insertion_point(module_scope)
