# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0bservice_api\"S\n\x18WifiI2CRelayWriteRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\r\x12\x12\n\ntimeout_ms\x18\x02 \x01(\r\x12\x12\n\nwrite_data\x18\x03 \x01(\x0c\"I\n\x14WifiI2CRelayResponse\x12#\n\x06result\x18\x01 \x01(\x0e\x32\x13.service_api.Result\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"e\n\x17WifiI2CRelayReadRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\r\x12\x12\n\ntimeout_ms\x18\x02 \x01(\r\x12\x12\n\nwrite_data\x18\x03 \x01(\x0c\x12\x11\n\tread_size\x18\x04 \x01(\r*@\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x0b\n\x07\x46\x41ILURE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULT']._serialized_start=293
  _globals['_RESULT']._serialized_end=357
  _globals['_WIFII2CRELAYWRITEREQUEST']._serialized_start=30
  _globals['_WIFII2CRELAYWRITEREQUEST']._serialized_end=113
  _globals['_WIFII2CRELAYRESPONSE']._serialized_start=115
  _globals['_WIFII2CRELAYRESPONSE']._serialized_end=188
  _globals['_WIFII2CRELAYREADREQUEST']._serialized_start=190
  _globals['_WIFII2CRELAYREADREQUEST']._serialized_end=291
# @@protoc_insertion_point(module_scope)
